<a href="https://colab.research.google.com/github/alipatel65/Hikmah-Lessons/blob/main/Hikmah_Lesson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Before We Begin

#### **What is Google Co-Lab**

Google Co-Lab is a place where you can come and code whenever you want! Within this notebook, you can write code and see how it works with cool visuals. You can also invite your friends to join you if you share the link with them.

#### **Starting the Notebook**

1. Head to the 'File' button located in the top left
2. Scroll down until you find 'Save a copy in Drive' and click it
3. Now you're ready to follow along and have fun!!

#### **How the Notebook Works**
1. The box that all these words are in is called a "cell"
2. If you want to see what what the cell might want to show you, then press the **Shift** and **Enter** keys at the same time
3. We call this "running the cell"

[link text](https://)# Part 1.) Python

![python clipart 2.png]()

#### **What is Python?**
- Not a snake
- Computers don't understand or speak English
- In order for us to tell it what to do, we need to talk to them in a language that they know
- Python is one of the many languages that computers understand

#### **Why Python?**
- It's a simple language to learn
- It is good for working with numbers
- It does everything really fast

#### Let's try a few examples to see how Python works

In [ ]:
# Let's see the computer say Salam to us
# Run this cell (Shift & Enter)

print("Salam, Saeed")

Salam, Saeed

In [ ]:
"I think that these people are more NO MISTAKES than Everyone makes mistakes"

'I think that these people are more NO MISTAKES than Everyone makes mistakes'

In [ ]:
Num1 =25
Num2 =54
Num3 =59
Num4 =32

Num1= Num2
Num3= Num2
Num2= Num4
Num1= Num3

In [ ]:
Num1= Num2
Num3= Num2
Num2= Num4
Num1= Num3

Num1

32

In [ ]:
# In the code below, look at where it says "Name"
# Replace "Name" with your first name
# Run this cell (Shift & Enter)

print("Salam, Saeedito")

Salam, Saeedito

In [ ]:
# Run this cell (Shift & Enter)

print("Coding is fun and these teachers are not always cool!")

Coding is fun and these teachers are not always cool!

# Part 2.) Types of Data

![number line clipart.gif]()

Python understands words and numbers just like we do, but it's called something different.

- Words are called **strings**
- Numbers are called **integers**
---
#### Strings
- Must always have quotations around them
- Words: "fruit", "apple", "orange"
- Sentence: "Tomatoes are fruits."

#### Integers
- You can type these just as you normally do
- Examples: 2, 4, 6, 8

In [ ]:
# Example of a string

("Give me some money")

'Give me some money'

In [ ]:
# Example of an integer

100000

100000

In [ ]:
# A number can be a string

"Brownies are delicious"

'Brownies are delicious'

In [ ]:
# Type your name as a string below this line

"Saeed ia a muslim."

'Saeed ia a muslim.'

In [ ]:
# Type in your favorite number below this line

"anything that has a 9"

'anything that has a 9'

In [ ]:
# Type in your birthday as a string below this line

"August 13, 2011"

'August 13, 2011'

# Part 3.) Expressions

Expressions use data types to give the computer something more complex to think about.
- Most expressions will be simple math
- Expressions can also include strings as well
---
We'll do a few examples below:
- Addition (+)
- Subtraction (-)
- Multiplication (*)
- Division (/)
- Strings

In [ ]:
# Addition Example 1

37/1234

0.029983792544570502

In [ ]:
# Addition Example 2

23485 + 32234 + 48543

104262

In [ ]:
# Pick two or more numbers and add them

12345678910*12345678910

152415787748818788100

In [ ]:
# Subtration Example 1

11 - 15

-4

In [ ]:
# Subtration Example 2

21 - 3

18

In [ ]:
# Pick two or more numbers and subract them

93845683746-87264981

93758418765

In [ ]:
# Multiplication Example 1

3456*34

117504

In [ ]:
# Multiplication Example 2

100 * 1000000000000000000000

100000000000000000000000

In [ ]:
# Pick two or more numbers and multiply them

1234*451

556534

In [ ]:
# Division Example 1

13454786744535423414/6152467531737261246326

0.0021868927670287467

In [ ]:
# Division Example 2

1 / 4

0.25

In [ ]:
# Pick two numbers and divide them

In [ ]:
# Will this work?

"Saeed is a muslim" *200

'Saeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslimSaeed is a muslim'

In [ ]:
# Let's see what happens here

"ice"+"cream"

'icecream'

In [ ]:
# Will this work?

"Race" + "car"

'Racecar'

In [ ]:
# Will this work?

"I like pickles! " * 50

'I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! I like pickles! '

In [ ]:
# High schoolers: Can you come up with an expression that repeats "Hikmah" two times and "Brentwood" three times

(

'hikmah'

# Part 4.) Assignment Statements

In the real world, we have a lot of random numbers and other pieces of data that we need to keep track of. We can use an assignment statement to do this.

---
- You can use a random **letter** or **word** and tell it to remember an expression
- We call this random letter or word a "Variable"
- Remember that expressions include strings and integers
- We use an equal (=) sign to tell the computer that we want to assign a variable to an expression
---


```
# How we make an assignment
variable = expression
```

In [ ]:
# Let's take a look at this basic assignment statement

x = "give me money"

In [ ]:
# What is x?

x

'give me money'

In [ ]:
# Look at this assignment statement

s = 4352

In [ ]:
# What is y?

s

4352

In [ ]:
# Let's assign z to something

z =1

In [ ]:
# Add y and z together

z + s

4353

In [ ]:
# Try adding x and y together. What happens here?

x + s

16697

In [ ]:
# I'm going to change the value of x

x = 12345

In [ ]:
# Now add x and y

x + z

12346

In [ ]:
# Let's see something more complex

cat = 5
dog = 4
bird = 'chiky'

In [ ]:
# What is cat - dog?

cat - dog

1

In [ ]:
from traitlets.config.application import ApplicationError
# Try the example from the slides (Apples and Oranges)

orange = 345457
apple =4315241
total = orange + apple
total

4660698

In [ ]:
# Try the example from the slides (Length and Width)

In [ ]:
# High schoolers: Create two variables called num1 and num2 and assign them to two different integer values of your choice.
#                 Swap the values of num1 and num2 using assignment statements.
num1 = 41356432
num2 =4765232100010
num1 = num2
num1

4765232100010

In [ ]:
# High schoolers: Assign the String "Hello" to a variable called greeting,
# then add the String " world!" to it and assign the resulting String to a variable called message.
greeting = "hello" "world"
greeting
message = "world"
message + greeting

'worldhelloworld'

# Part 5.) Arrays

An array is just another way of saying a list. It is a really good way to store data so we can use it later.

#### **How do I make an array?**
Input: make_array(1, 2, 3)

Output: array([1, 2, 3])

#### **What else should I know?**
- Every part of the array should be the same data type (integer or string)
- We are able to assign arrays to variables in assignment statements
- We can do math on arrays!

In [ ]:
import numpy as np
from datascience import *

In [ ]:
# Let's make an array

1 + make_array(131, 329, 476)

array([132, 330, 477])

In [ ]:
# Let's assign the array

Saeed = make_array(132, 528, 763)
Saeed

array([132, 528, 763])

In [ ]:
# Let's take each number in the array and add 1 to it

Saeed * 142354617238561426782359451959

array([18790809475490108335271447658588, 75163237901960433341085790634352,
       108616572953022368634940261844717], dtype=object)

In [ ]:
# Let's subtract each number by 2

Saeed - 523646153276124823476136298762198725491827590091287198374643770101129999999833333333333333333333333333333333333333333333333333576012937690126

array([ -523646153276124823476136298762198725491827590091287198374643770101129999999833333333333333333333333333333333333333333333333333576012937689994,
       -523646153276124823476136298762198725491827590091287198374643770101129999999833333333333333333333333333333333333333333333333333576012937689598,
       -523646153276124823476136298762198725491827590091287198374643770101129999999833333333333333333333333333333333333333333333333333576012937689363], dtype=object)

In [ ]:
# Make your own array and assign it to a variable
Saeed / 76394128674354126239546900476000005914761590257365294712592461505602916501924367869201549344875012947629387190756948576666666666666749210477777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777135666666666666666666109283476853777777777777777777777777777711111111011111111110463331

array([0.0, 5e-324, 1e-323], dtype=object)

In [ ]:
# Add 10 to every number in your array
Saeed + 1274896780392796140888886234566666666666666666666666666666666666666666663444333

array([ 1274896780392796140888886234566666666666666666666666666666666666666666663444465,
       1274896780392796140888886234566666666666666666666666666666666666666666663444861,
       1274896780392796140888886234566666666666666666666666666666666666666666663445096], dtype=object)

In [ ]:
# Multiply each number by 3
Saeed * 9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999

array([ 1319999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999868,
       5279999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999472,
       7629999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999237], dtype=object)

# Part 6.) Call Functions

Call functions help us **better understand** the data that is inside of our arrays. We can find:
- The biggest number
- The smallest number
- The average number
- The length of the entire array
---
Here is how we create and use a call function:

*name of function*(array)

---
Common Call Functions:
- max(array) --> gets us the **largest** number
- min(array) --> gets us the **smallest** number
- mean(array) --> gets us the **average**
- len(array) --> gives us the length of the array

In [ ]:
# Let's make a long array of numbers and assign it

long_array = make_array(13, 8, 3, 5, 2, 11, 14, 12, 1, 4, 15, 1, 7, 4, 10, 21, 20, 14, 3, 9)
long_array

array([13,  8,  3,  5,  2, 11, 14, 12,  1,  4, 15,  1,  7,  4, 10, 21, 20,
       14,  3,  9])

In [ ]:
# Let's find the biggest number

max(long_array)

21

In [ ]:
# Let's find the smallest number

min(long_array)

1

In [ ]:
# Let's find how long the array is

len(long_array)

20

In [ ]:
# Make your own array

In [ ]:
# Find the biggest number and assign it to a variable called "max"

In [ ]:
# Find the smallest number and assign it to a variable called "min"

In [ ]:
# Add max and min together

In [ ]:
# Find the length of the array

In [ ]:
# High schoolers: When we create a new call function, it looks something like this:
def my_func(a):
  return a
# Here a is a parameter that gets passed into the function
# Fill in the return statement for a function that takes in two parameters and multiplies them together.
# Then, use it to multiply the two maximum values in the below arrays and assign the result to a variable called most_max
array1 = make_array(10, 13, 17)
array2 = make_array(2, 6, 11, 5, 23)

def multiply(a, b):
  return ...

391

# Part 7.) Tables

Tables are a great way to store and organize a large amount of data. We can easily find the information we need!

---
#### **What are some things to know about tables?**
- They consists of rows (left to right) and columns (top to bottom)
- We can turn columns into arrays to do math on them

#### **How do I create tables?**
- Table().with_columns("Name of Column1", array1, "Name of Column 2", array 2)
- Each column you make must have an array within it
- All arrays must be the same length

In [ ]:
# We are going to make a simple table about ice cream

In [ ]:
# Start off with creating our data using arrays

flavors = make_array('vanilla', 'chocolate', 'strawberry', 'pistachio', 'cookies & cream')
prices = make_array(3.0, 3.0, 3.50, 4.5, 4.0)
amount_sold = make_array(10, 18, 11, 22, 19)

print(flavors)
print(prices)
print(amount_sold)

['vanilla' 'chocolate' 'strawberry' 'pistachio' 'cookies & cream']
[ 3.   3.   3.5  4.5  4. ]
[10 18 11 22 19]

In [ ]:
# Create the ice cream table

ice_cream = Table().with_columns("flavor", flavors, "price", prices, "amount sold", amount_sold)
ice_cream

flavor          | price | amount sold
vanilla         | 3     | 10
chocolate       | 3     | 18
strawberry      | 3.5   | 11
pistachio       | 4.5   | 22
cookies & cream | 4     | 19

In [ ]:
# Let's find the biggest amount sold

max(ice_cream.column('amount sold'))

22

In [ ]:
# Let's find the most expensive price

max(ice_cream.column('price'))

4.5

In [ ]:
# Let's sort the table by amount sold

ice_cream.sort('amount sold', descending=True)

flavor          | price | amount sold
pistachio       | 4.5   | 22
cookies & cream | 4     | 19
chocolate       | 3     | 18
strawberry      | 3.5   | 11
vanilla         | 3     | 10

In [ ]:
# Create an array with the names of four fruits

In [ ]:
# Create an array the color of each fruit

In [ ]:
# Create an array with the price of each fruit

In [ ]:
# Create an array with the amount of each fruit that was sold

In [ ]:
# Create a table with all of those arrays
# The column names should be "fruit" "color" "price" "amount sold"

In [ ]:
# Find the highest price

In [ ]:
# Find the lowest price

In [ ]:
# Find the lowest amount sold

In [ ]:
# HARD PROBLEM
# Find the amount of money you made from selling each fruit